doc/urls.py
from django.urls import path, include
from doc import views

app_name = 'doc'

urlpatterns = [
    # These url patterns are commented out because the corresponding views.py
    # has not been implemented yet. Please both the url Name and views are subject to change based on need
    # and whether they are function or class based views (see above)
    #path('', views.doc_view, name='doc'),
    path('upload/', views.upload_document, name='upload_document'),
    path('<int:document_id>/', views.document_detail, name='document_detail'),
    path('<int:document_id>/delete/', views.delete_document, name='delete_document'),
    path('<int:document_id>/like/', views.like_document, name='like_document'),
    path('<int:document_id>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('search/', views.search_documents, name='search_documents'),
    # path('<int:doc_id>', views.DocView.as_view, name='doc'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views

urlpatterns = [
    #Some of these url patterns are commented out because the corresponding views.py
    # has not been implemented yet. Please both the url Name and views are subject to change based on need
    # and whether they are function or class based views (see above)
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('profile/', include('profiles.urls')),

    path('myprojects/', include('projects.urls')),
    path('classes/', include('classes.urls')),
]

profiles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'profiles'
urlpatterns = [
    # These url patterns are commented out because the corresponding views.py
    # has not been implemented yet. Please both the url Name and views are subject to change based on need
    # and whether they are function or class based views (see above)

    path('<str:username>/', views.profile_view, name='profile'),
    path('<str:username>/edit/', views.edit_profile_view, name='editprofile'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
import boto3
from django.conf import settings

# Create your models here.

def upload_to_profile_folder(instance, filename):
    return f'profiles/{instance.user.username}/{filename}'

class Profile(models.Model):
    USER_TYPE_CHOICES = [('Common', 'Common'),
                         ('PMA Admin', 'PMA Admin'),
                         ('Anonymous', 'Anonymous')
                         ]
    
    YEAR_CHOICES = [ ('First Year','First Year'),
                    ('Second Year','Second Year'),
                    ('Third Year','Third Year'),
                    ('Fourth Year','Fourth Year')
                    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    computing_id = models.TextField(max_length=10, unique=True, blank=True, null=True, default=None)
    major = models.TextField(max_length=50, blank=True, null=True)
    year = models.CharField(max_length=15, choices=YEAR_CHOICES, blank=True, null=True)
    user_type = models.CharField(max_length=20, default='Common', choices=USER_TYPE_CHOICES)
    date_joined = models.DateField(auto_now_add=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    profile_pic = models.FileField(upload_to=upload_to_profile_folder, default='profiles/images/testpfp.png')

    def __str__(self):
        return self.user.username

    def delete_file_from_s3(self, file_key):
        """This is a helper method to delete a file from S3."""
        try:
            s3 = boto3.client(
                's3',
                aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                region_name=settings.AWS_S3_REGION_NAME
            )
            s3.delete_object(
                Bucket=settings.AWS_STORAGE_BUCKET_NAME,
                Key=file_key
            )
            return True
        except Exception as e:
            print(f"Error deleting file from S3: {e}")
            return False

    def save(self, *args, **kwargs):
        # Check if the profile picture is being updated
        if self.pk:
            old_profile = Profile.objects.get(pk=self.pk)
            if old_profile.profile_pic and self.profile_pic != old_profile.profile_pic:
                # Delete the old profile picture
                self.delete_file_from_s3(old_profile.profile_pic.name)

        super().save(*args, **kwargs)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from .widgets import CustomClearableFileInput


class ProfileForm(forms.ModelForm):
    YEAR_CHOICES = [
        ('First Year', 'First Year'),
        ('Second Year', 'Second Year'),
        ('Third Year', 'Third Year'),
        ('Fourth Year', 'Fourth Year')
    ]

    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
    )
    year = forms.ChoiceField(
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        exclude_admin_fields = kwargs.pop('exclude_admin_fields', False)
        super().__init__(*args, **kwargs)

        if exclude_admin_fields:
            del self.fields['year']
            del self.fields['major']
            del self.fields['bio']

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'year', 'major', 'computing_id', 'bio', 'profile_pic']
        widgets = {
            'major': forms.TextInput(attrs={'class': 'form-control'}),
            'computing_id': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'profile_pic': CustomClearableFileInput(attrs={
                'class': 'form-control',
                'accept': 'image/png, image/jpeg',  # Restrict file types
            }),
        }

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .models import Profile
from django.contrib.auth.models import User
from .forms import ProfileForm
    
@login_required
def profile_view(request, username):
    if request.user.username == 'guest':
        messages.warning(request, "Access restricted.")
        return redirect('home')
    
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'profiles/profile.html', {'profile': profile})

@login_required
def edit_profile_view(request, username):
    user = get_object_or_404(User, username=username)

    if user != request.user:
        return redirect('profiles:profile', username)

    profile = request.user.profile

    exclude_admin_fields = profile.user_type == 'PMA Admin'

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile, exclude_admin_fields=exclude_admin_fields)
        if form.is_valid():
            form.save()
            return redirect('profiles:profile', username)

    else:
        form = ProfileForm(instance=profile, initial={
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }, exclude_admin_fields=exclude_admin_fields)

    return render(request, 'profiles/editprofile.html', {'form': form})

profiles/templates/profiles/editprofile.html
{% extends 'base.html' %}

{% block content %} 
<div class="container mt-4">

    {% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field, errors in form.errors.items %}
                <li><strong>{{ field|capfirst }}</strong>: {{ errors|join:", " }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="row justify-content-center">
        <div class="col-md-8">

             <div class="mb-3">
                <a href="{% url 'profiles:profile' request.user.username %}" class="btn btn-outline-primary">
                    <i class="bi bi-arrow-left"></i> Back to Profile
                </a>
            </div>

            
            <h2 class="text-center mb-4">Edit Profile</h2>
            <div class="card">
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- First Name and Last Name -->
                        <div class="mb-3">
                            <label for="id_first_name" class="form-label">First Name</label>
                            {{ form.first_name }}
                        </div>
                        <div class="mb-3">
                            <label for="id_last_name" class="form-label">Last Name</label>
                            {{ form.last_name }}
                        </div>
                        {% if form.year %}
                            <div class="mb-3">
                                <label for="id_year" class="form-label">Year</label>
                                {{ form.year }}
                            </div>
                        {% endif %}

                        {% if form.major %}
                            <div class="mb-3">
                                <label for="id_major" class="form-label">Major</label>
                                {{ form.major }}
                            </div>
                        {% endif %}

                        <div class="mb-3">
                            <label for="id_computing_id" class="form-label">Computing ID</label>
                            {{ form.computing_id }}
                            <div class="form-text fw-bold text-primary">
                                Your Computing ID is required and must be unique.
                            </div>
                            {% if form.computing_id.errors %}
                                <div class="text-danger">
                                    {% for error in form.computing_id.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>


                        {% if form.bio %}
                        <div class="mb-3">
                            <label for="id_bio" class="form-label">Bio</label>
                            {{ form.bio }}
                        </div>
                        {% endif %}

                        <div class="mb-3 text-center">
                            <label for="id_profile_pic" class="form-label">Profile Picture</label>
                            {{ form.profile_pic }}
                        </div>

                        <!-- Submit and Cancel Buttons -->
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <button type="submit" class="btn btn-success">Save Changes</button>
                            <a href="{% url 'profiles:profile' request.user.username %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Profile - UVANotes
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-4">
        <div class="col-md-3 justify-content-between">
            <!--profile pic-->
            <img src="{{ profile.profile_pic.url }}" alt="Profile Picture" class="img-thumbnail rounded-circle">
            <!--username-->
            <h4 class="mt-2">{{ profile.user.username }}</h4>

        </div>
        <div class="col-md-9">
            <div class="d-flex justify-content-between align-items-center">
                <h2>{{ profile.user.username }}</h2>
                        <a href="{% url 'profiles:editprofile' request.user.username %}" class="btn btn-primary">Edit Profile</a>
            </div>
            <p><strong>Name:</strong> {{ profile.user.first_name }} {{ profile.user.last_name }}</p>
            <p><strong>Email:</strong> {{ profile.user.email }}</p>
            <p><strong>Date Joined:</strong> {{ profile.date_joined }}</p>
            {% if profile.user_type != 'PMA Admin' %}
            <p><strong>Year:</strong> {{ profile.year }}</p>
            <p><strong>Major:</strong> {{ profile.major }}</p>
            <p><strong>Computing ID:</strong> {{ profile.computing_id }}</p>
            <h5>Bio:</h5>
            <ul>
                {{ profile.bio }}  
            </ul>
            {% else%}
            <h3><strong>PMA ADMIN</strong></h3>
            {% endif%}

        </div>
    </div>

    <!--<h4>Classes Taken:</h4>
    <div class="col-md-12">
        <ul class="list-inline">
            <li class="list-inline-item">CS 3240</li>
            <li class="list-inline-item">CS 3130</li>
            <li class="list-inline-item">CS 3100</li>
            <li class="list-inline-item">APMA 3100</li>
        </ul>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <p><em>Note:</em> This page is currently set up to show what is possible for the profile page.</p>
        </div>
    </div>--> 
</div>
{% endblock %}